package Auctioning;


/**
* Auctioning/AuctionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/auctioning.idl
* Tuesday, 30 November 2010 12:56:02 o'clock GMT
*/

public interface AuctionOperations 
{
  Auctioning.b getItem (String itemRef);
  Auctioning.b[] getAllItems ();
  String placeBid (String itemRef, String poster, double bid);
  void addItem (Auctioning.b b);
  String login (String uname, String password);
  void logout (String uname);
} // interface AuctionOperations
