package Auctioning;


/**
* Auctioning/b.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/auctioning.idl
* Tuesday, 30 November 2010 12:56:02 o'clock GMT
*/

public final class b implements org.omg.CORBA.portable.IDLEntity
{
  public String itemRef = null;
  public String poster = null;
  public String itemName = null;
  public String itemDesc = null;
  public double minBid = (double)0;
  public long endTime = (long)0;
  public double winningBid = (double)0;
  public String winningBidder = null;

  public b ()
  {
  } // ctor

  public b (String _itemRef, String _poster, String _itemName, String _itemDesc, double _minBid, long _endTime, double _winningBid, String _winningBidder)
  {
    itemRef = _itemRef;
    poster = _poster;
    itemName = _itemName;
    itemDesc = _itemDesc;
    minBid = _minBid;
    endTime = _endTime;
    winningBid = _winningBid;
    winningBidder = _winningBidder;
  } // ctor

} // class b
