package Auctioning;

/**
* Auctioning/bHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/auctioning.idl
* Tuesday, 30 November 2010 12:56:02 o'clock GMT
*/

public final class bHolder implements org.omg.CORBA.portable.Streamable
{
  public Auctioning.b value = null;

  public bHolder ()
  {
  }

  public bHolder (Auctioning.b initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Auctioning.bHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Auctioning.bHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Auctioning.bHelper.type ();
  }

}
