package Auctioning;


/**
* Auctioning/itemInfoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/auctioning.idl
* Tuesday, 30 November 2010 12:56:02 o'clock GMT
*/

abstract public class itemInfoHelper
{
  private static String  _id = "IDL:Auctioning/itemInfo:1.0";

  public static void insert (org.omg.CORBA.Any a, Auctioning.b that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Auctioning.b extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = Auctioning.bHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (Auctioning.itemInfoHelper.id (), "itemInfo", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Auctioning.b read (org.omg.CORBA.portable.InputStream istream)
  {
    Auctioning.b value = null;
    value = Auctioning.bHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Auctioning.b value)
  {
    Auctioning.bHelper.write (ostream, value);
  }

}
