package Auctioning;


/**
* Auctioning/itemsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/auctioning.idl
* Tuesday, 30 November 2010 12:56:02 o'clock GMT
*/

public final class itemsHolder implements org.omg.CORBA.portable.Streamable
{
  public Auctioning.b value[] = null;

  public itemsHolder ()
  {
  }

  public itemsHolder (Auctioning.b[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Auctioning.itemsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Auctioning.itemsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Auctioning.itemsHelper.type ();
  }

}
