package Dealing;


/**
* Dealing/b.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dealing.idl
* Friday, 26 November 2010 16:43:44 o'clock GMT
*/

public final class b implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public int number = (int)0;

  public b ()
  {
  } // ctor

  public b (String _name, int _number)
  {
    name = _name;
    number = _number;
  } // ctor

} // class b
