package Dealing;

/**
* Dealing/bHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dealing.idl
* Friday, 26 November 2010 16:43:44 o'clock GMT
*/

public final class bHolder implements org.omg.CORBA.portable.Streamable
{
  public Dealing.b value = null;

  public bHolder ()
  {
  }

  public bHolder (Dealing.b initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Dealing.bHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Dealing.bHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Dealing.bHelper.type ();
  }

}
