package Dealing;


/**
* Dealing/buysHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dealing.idl
* Friday, 26 November 2010 16:43:44 o'clock GMT
*/

public final class buysHolder implements org.omg.CORBA.portable.Streamable
{
  public Dealing.b value[] = null;

  public buysHolder ()
  {
  }

  public buysHolder (Dealing.b[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Dealing.buysHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Dealing.buysHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Dealing.buysHelper.type ();
  }

}
