package Dealing;


/**
* Dealing/DealOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dealing.idl
* Friday, 26 November 2010 16:43:44 o'clock GMT
*/

public interface DealOperations 
{
  void addBuy (Dealing.b b);
  Dealing.b[] getBuys ();
} // interface DealOperations
