package Dealing;

/**
* Dealing/DealHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dealing.idl
* Friday, 26 November 2010 16:43:44 o'clock GMT
*/

public final class DealHolder implements org.omg.CORBA.portable.Streamable
{
  public Dealing.Deal value = null;

  public DealHolder ()
  {
  }

  public DealHolder (Dealing.Deal initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Dealing.DealHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Dealing.DealHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Dealing.DealHelper.type ();
  }

}
