package Dealing;


/**
* Dealing/DealHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dealing.idl
* Friday, 26 November 2010 16:43:44 o'clock GMT
*/

abstract public class DealHelper
{
  private static String  _id = "IDL:Dealing/Deal:1.0";

  public static void insert (org.omg.CORBA.Any a, Dealing.Deal that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Dealing.Deal extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Dealing.DealHelper.id (), "Deal");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Dealing.Deal read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DealStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Dealing.Deal value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Dealing.Deal narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Dealing.Deal)
      return (Dealing.Deal)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Dealing._DealStub stub = new Dealing._DealStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Dealing.Deal unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Dealing.Deal)
      return (Dealing.Deal)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Dealing._DealStub stub = new Dealing._DealStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
